/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author omeraran
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_password = new javax.swing.JLabel();
        tik_password = new javax.swing.JCheckBox();
        text_nickname = new javax.swing.JTextField();
        send_button = new javax.swing.JButton();
        label_nickname = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        label_header = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_password.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        label_password.setText("passsword : ");

        tik_password.setFont(new java.awt.Font("Chalkduster", 1, 8)); // NOI18N
        tik_password.setText("show password");
        tik_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tik_passwordActionPerformed(evt);
            }
        });

        send_button.setBackground(new java.awt.Color(255, 255, 255));
        send_button.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        send_button.setText("submit");
        send_button.setToolTipText("");
        send_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_buttonActionPerformed(evt);
            }
        });

        label_nickname.setBackground(new java.awt.Color(255, 0, 0));
        label_nickname.setFont(new java.awt.Font("Chalkduster", 1, 14)); // NOI18N
        label_nickname.setText("nickname : ");

        text_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passwordActionPerformed(evt);
            }
        });

        label_header.setFont(new java.awt.Font("Chalkduster", 1, 48)); // NOI18N
        label_header.setForeground(new java.awt.Color(123, 124, 230));
        label_header.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(send_button)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_header)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_password)
                            .addComponent(label_nickname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_password, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(text_nickname))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tik_password)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_header, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nickname)
                    .addComponent(text_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_password)
                    .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tik_password))
                .addGap(54, 54, 54)
                .addComponent(send_button)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_buttonActionPerformed
        String test_nickname = "gizem" ;
        String test_password = "gizemömer6337" ;
        
        if(text_nickname.getText().equals(test_nickname) && text_password.getText().equals(test_password)){
            
            JOptionPane.showInternalMessageDialog(null, "Login Successful");
        }
        
        else if (text_nickname.getText().equals(test_nickname) && text_password.getText() != test_password){
            JOptionPane.showInternalMessageDialog(null,"password was false");
        }
        else if (text_nickname.getText()!=test_nickname && text_password.getText().equals( test_password)){
            JOptionPane.showInternalMessageDialog(null,"nickname was false");
        }
        
        else{
        JOptionPane.showInternalMessageDialog(null,"all infos was wrong");
        }
    }//GEN-LAST:event_send_buttonActionPerformed

    private void tik_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tik_passwordActionPerformed
       if(tik_password.isSelected()){
       text_password.setEchoChar((char)0);
       }
       else{
       text_password.setEchoChar('*');
       }
    }//GEN-LAST:event_tik_passwordActionPerformed

    private void text_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label_header;
    private javax.swing.JLabel label_nickname;
    private javax.swing.JLabel label_password;
    private javax.swing.JButton send_button;
    private javax.swing.JTextField text_nickname;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JCheckBox tik_password;
    // End of variables declaration//GEN-END:variables
}
